### PR TITLE
Broken link :)

### PR DESCRIPTION
**Pull request by davibicudo**

### CODE REVIEW

**Comment by sebhoerl** [comment]
Thanks, Davi. There was a problem with Travis lately. Could you maybe add a space or something like that somewhere and try again? The build seems to be hanging.

**Comment by davibicudo** [comment]
Just did, hope it triggers Travis correctly!
The Nested Logit PR caught my attention. Are you working on it for a publication?

**Comment by sebhoerl** [comment]
@davibicudo  The Nested Logit works in principle, it is even unit tested and there are examples in the tests... there is a short list of things that are missing, which are mainly configuration stuff. Yes, this could become a publications, but it is not top priority right now. Do yo uthink it would be useful for you? We can have a more detailed discussion via email.

**Comment by davibicudo** [comment]
@sebhoerl we're testing and discussing if/how to use DMC, so nothing specific right now but it is nice to see that nested logit is now also an option, certainly an added value :)
Looking at the code, I saw the examples for building nests between similar modes (red/blue bus), but how about the tour-based model? Could we have e.g. two nests: "car-based tour" vs "pt-based tour", where the latter has then multiple trip combinations of walk/pt?

**Comment by sebhoerl** [comment]
I would need to check agian, I put this up before Christmas :) But I think it should be independent whether it is trip- or tour-based. The important points are the canddiates (and I see that apparently I already added NestedTripCandidate and NestedTourCandidate):
https://github.com/matsim-eth/discrete-mode-choice/tree/feature/nested_logit/src/main/java/ch/ethz/matsim/discrete_mode_choice/model/nested

and the other part is the NestedLogitSelector, which is independent of whether we look at a tour or trip. So to summarize, from what I remember and what I just had time to look up it looks like this should already work.

If you feel like it, you could construct a little example in the unit tests ;)

**Pull request merged**
